BB103_Pronia/BB103_Pronia/Areas/Manage/ViewModels/Product/CreateProduct.cs
using System.ComponentModel.DataAnnotations;

namespace BB103_Pronia.Areas.Manage.ViewModels.Product
{
    public class CreateProduct
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string? SKU { get; set; }
        public int CategoryId { get; set; }
        public List<int> TagIds { get; set; }
        [Required]
        public IFormFile MainPhoto { get; set; }
        [Required]
        public IFormFile HoverPhoto { get; set; }
        public List<IFormFile>? Photos { get; set; }


    }
}

BB103_Pronia/BB103_Pronia/Areas/Manage/ViewModels/Product/ListProduct.cs
namespace BB103_Pronia.Areas.Manage.ViewModels.Product
{
    public class ListProduct
    {
        public string Name { get; set; }
        public double Price { get; set; }
        public Category Category { get; set; }
        public List<Tag> Tags { get; set; }


    }
}

BB103_Pronia/BB103_Pronia/Areas/Manage/ViewModels/Product/UpdateProduct.cs
using System.ComponentModel.DataAnnotations;

namespace BB103_Pronia.Areas.Manage.ViewModels.Product
{
    public class UpdateProduct
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string? SKU { get; set; }
        [Required]
        public int? CategoryId { get; set; }
        public List<int> TagIds { get; set; }
        public IFormFile? MainPhoto { get; set; }
        public IFormFile? HoverPhoto { get; set; }
        public List<IFormFile>? Photos { get; set; }
        public List<ProductImageVm>? ProductImagesVm { get; set; }
        public List<int>? ImageIds { get; set; }
    }
    public class ProductImageVm
    {
        public int Id { get; set; }
        public bool? IsPrime { get; set; }
        public string ImgUrl { get; set; }
    }

}

BB103_Pronia/BB103_Pronia/Models/Product.cs
namespace BB103_Pronia.Models
{
    public class Product:BaseEntity
    {
        public string  Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string SKU { get; set; }
        public int? CategoryId { get; set; }
        public Category? Category { get; set; }
        public List<ProductImage>? ProductImages { get; set; }
        public List<ProductTag> ProductTags { get; set; }
        
        public bool IsDeleted { get; set; }
    }
}

BB103_Pronia/BB103_Pronia/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace BB103_Pronia.Controllers
{
    
    public class CartController : Controller
    {
        AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public CartController(AppDbContext context,UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
           

            List<BasketItemVm> basketItems = new List<BasketItemVm>();
            if (User.Identity.IsAuthenticated)
            {
                AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);
                List<BasketItem> userBasket = await _context.BasketItems
                    .Where(b=>b.AppUserId==user.Id && b.OrderId == null)
                    .Include(b=>b.Product)
                    .ThenInclude(p=>p.ProductImages
                    .Where(pi=>pi.IsPrime==true)).ToListAsync();
                foreach(var item in userBasket)
                {
                    basketItems.Add(new BasketItemVm()
                    {
                        Price = item.Price,
                        Count=item.Count,
                        ImgUrl=item.Product.ProductImages.FirstOrDefault().ImgUrl,
                        Name=item.Product.Name
                    });
                }

            }
            else
            {


                List<BasketCookieVm> basketCookies = new List<BasketCookieVm>();
                if (Request.Cookies["Basket"] != null)
                {
                    basketCookies = JsonConvert.DeserializeObject<List<BasketCookieVm>>(Request.Cookies["Basket"]);
                    foreach (var item in basketCookies)
                    {
                        Product product = _context.Products.Where(p => p.IsDeleted == false).Include(p => p.ProductImages.Where(pi => pi.IsPrime == true)).FirstOrDefault(p => p.Id == item.Id);

                        if (product == null)
                        {

                            continue;
                        }

                        basketItems.Add(new BasketItemVm()
                        {
                            Id = item.Id,
                            Name = product.Name,
                            Price = product.Price,
                            ImgUrl = product.ProductImages.FirstOrDefault().ImgUrl,
                            Count = item.Count
                        });
                    }
                }

                Response.Cookies.Append("Basket", JsonConvert.SerializeObject(basketCookies));

            }
                return View(basketItems);
            
            
        }
        public async Task<IActionResult> AddBasket(int id)
        {
            var product = _context.Products.Where(p => p.IsDeleted == false).FirstOrDefault(p => p.Id == id);
            if (product == null) return NotFound();

            if(User.Identity.IsAuthenticated)
            {
                AppUser user=await _userManager.FindByNameAsync(User.Identity.Name);
                BasketItem existItem = await _context.BasketItems
                    .FirstOrDefaultAsync(p => p.AppUserId == user.Id && p.ProductId == product.Id && p.OrderId == null);
                if(existItem!=null)
                {
                    existItem.Count++;
                }
                else
                {
                    BasketItem basketItem = new BasketItem()
                    {
                        AppUser = user,
                        Product = product,
                        Count = 1,
                        Price = product.Price,

                    };
                    _context.BasketItems.Add(basketItem);

                }
               await _context.SaveChangesAsync();
               

            }
            else
            {
                List<BasketCookieVm> basket;
                if (Request.Cookies["Basket"] == null)
                {
                    BasketCookieVm basketCookieVm = new BasketCookieVm()
                    {
                        Id = id,
                        Count = 1
                    };
                    basket = new List<BasketCookieVm>();
                    basket.Add(basketCookieVm);
                }
                else
                {
                    basket = JsonConvert.DeserializeObject<List<BasketCookieVm>>(Request.Cookies["Basket"]);
                    var existBasket = basket.FirstOrDefault(p => p.Id == id);
                    if (existBasket != null)
                    {
                        existBasket.Count += 1;
                    }
                    else
                    {
                        BasketCookieVm basketCookieVm = new BasketCookieVm()
                        {
                            Id = id,
                            Count = 1
                        };
                        basket.Add(basketCookieVm);
                    }
                }
                var json = JsonConvert.SerializeObject(basket);
                Response.Cookies.Append("Basket", json);
            }




            

            return RedirectToAction(nameof(Index), "Home");
        }

        [Authorize]
        public async Task<IActionResult> Checkout()
        {
            AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);
            OrderVm orderVm = new OrderVm();
            orderVm.BasketItems = await _context.BasketItems
                .Where(b => b.AppUserId == user.Id&&b.OrderId==null).Include(b=>b.Product).ToListAsync();
            return View(orderVm);
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Checkout(OrderVm orderVm)
        {
           AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);
           if(!ModelState.IsValid)
            {
                orderVm.BasketItems = await _context.BasketItems
             .Where(b => b.AppUserId == user.Id && b.OrderId == null).Include(b => b.Product).ToListAsync();
                ModelState.AddModelError("Address", "Addresi mutleq doldurun");
                return View(orderVm);
            }
           var userBasketItems=await _context.BasketItems
             .Where(b => b.AppUserId == user.Id && b.OrderId == null).Include(b => b.Product).ToListAsync();
            double TotalPrice = 0;
            for(int i=0;i<userBasketItems.Count;i++)
            {
                TotalPrice+=userBasketItems[i].Price*userBasketItems[i].Count;
            }
            Order order = new Order()
            {
                BasketItems = userBasketItems,
                Address = orderVm.Address,
                AppUser = user,
                CreateDate = DateTime.Now,
                TotalPrice = TotalPrice,
                Code=CreateRandomCode.GenerateCode(5)
                
            };

            await _context.Orders.AddAsync(order);
            await _context.SaveChangesAsync();




            return RedirectToAction(nameof(Index),"Home");
        }

    }
}

BB103_Pronia/BB103_Pronia/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BB103_Pronia.Controllers
{
    public class ShopController : Controller
    {
        AppDbContext _context;

        public ShopController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }


        public async Task<IActionResult> Detail(int id)
        {
            //string cookie = Request.Cookies["Name"];


            //if(cookie == null) return NotFound();
            //var session = HttpContext.Session.GetString("Name");
            


               
            Product product = await
                _context.Products
                .Include(c => c.Category)
                .Include(img => img.ProductImages)
                .Include(pt => pt.ProductTags).ThenInclude(pt => pt.Tag)
                .FirstOrDefaultAsync(p => p.Id == id);
                
            if(product == null)
            {
                return NotFound();
            }
            DetailVm detailVm = new DetailVm()
            {
                Product = product,
                Products = _context.Products.Include(p => p.ProductImages).ToList()
            };
            return View(detailVm);
        }


        
        public IActionResult GetBasket()
        {
            var cookie = Request.Cookies["Basket"];

            return Content(cookie);
        }

    }
}

BB103_Pronia/BB103_Pronia/Views/Shared/Components/Product/Default.cshtml
@model List<Product>

<div class="product-item-wrap row">

    @foreach (var item in Model)
    {
       <div class="col-xl-3 col-md-4 col-sm-6">
        <div class="product-item">
            <div class="product-img">
                <a asp-controller="Shop" asp-action="Detail" asp-route-id=@item.Id>
                    <img class="primary-img"
                         src="~/Upload/Product/@item.ProductImages.FirstOrDefault(i=>i.IsPrime==true).ImgUrl"
                         alt="Product Images" />
                    <img class="secondary-img"
                         src="~/Upload/Product/@item.ProductImages.FirstOrDefault(i=>i.IsPrime==false).ImgUrl"
                         alt="Product Images" />
                </a>
                <div class="product-add-action">
                    <ul>
                        <li>
                            <a href="wishlist.html"
                               data-tippy="Add to wishlist"
                               data-tippy-inertia="true"
                               data-tippy-animation="shift-away"
                               data-tippy-delay="50"
                               data-tippy-arrow="true"
                               data-tippy-theme="sharpborder">
                                <i class="pe-7s-like"></i>
                            </a>
                        </li>
                        <li class="quuickview-btn"
                            data-bs-toggle="modal"
                            data-bs-target="#quickModal">
                            <a href="#"
                               data-tippy="Quickview"
                               data-tippy-inertia="true"
                               data-tippy-animation="shift-away"
                               data-tippy-delay="50"
                               data-tippy-arrow="true"
                               data-tippy-theme="sharpborder">
                                <i class="pe-7s-look"></i>
                            </a>
                        </li>
                        <li>
                            <a asp-action="AddBasket" asp-controller="Cart" asp-route-id=@item.Id
                               data-tippy="Add to cart"
                               data-tippy-inertia="true"
                               data-tippy-animation="shift-away"
                               data-tippy-delay="50"
                               data-tippy-arrow="true"
                               data-tippy-theme="sharpborder">
                                <i class="pe-7s-cart"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="product-content">
                <a class="product-name" href="shop.html">@item.Name</a>
                <div class="price-box pb-1">
                    <span class="new-price">$@item.Price</span>
                </div>
                <div class="rating-box">
                    <ul>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                    </ul>
                </div>
            </div>
        </div>
    </div> 
    }

    



</div>